### ISSUE TITLE
【依頼】ChatSpace挙動確認

### ISSUE THREAD

**Issue by fukuda-taichi** [fukuda-taichi/chat-space#7]
# IP
18.178.105.29

**Comment by kohei-isoda** [comment]
福田さん、ご提出ありがとうございます！
挙動確認させて頂いたところ、以下の不備が見受けられましたので修正をお願いします！

◯ フラッシュメッセージの配置が見本通りでない
[![Screenshot from Gyazo](https://gyazo.com/c4ea18cb61caf3931d78358d68ebf8ed/raw)](https://gyazo.com/c4ea18cb61caf3931d78358d68ebf8ed)

◯ 新規アカウント作成ページ（ユーザー情報編集ページも同様）が左に寄ってしまっている
[![Screenshot from Gyazo](https://gyazo.com/f6f86d6c2dd9b2a6516189473848e309/raw)](https://gyazo.com/f6f86d6c2dd9b2a6516189473848e309)

◯ 配色が指示書通りでない部分がある（以下画像参照）
[![Screenshot from Gyazo](https://gyazo.com/bcd1f797c263e04ec341311f7b490107/raw)](https://gyazo.com/bcd1f797c263e04ec341311f7b490107)

サーバーサイドは物凄く上手に出来ていたので、残るは見た目の部分のみです！
修正し次第、以下のChatSpace完了報告フォームを再度提出お願いします！
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by fukuda-taichi** [comment]
> [h](https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform)

修正しました。確認願いします！

**Comment by kohei-isoda** [comment]
再提出ありがとうございます！
確認させて頂いたのですが、全ての修正箇所において修正が見られませんでした。
お手数ですが本番環境にデプロイしたかどうかを確認して頂いて再度ご提出ください！
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by fukuda-taichi** [comment]
> 再提出ありがとうございます！
> 確認させて頂いたのですが、全ての修正箇所において修正が見られませんでした。
> お手数ですが本番環境にデプロイしたかどうかを確認して頂いて再度ご提出ください！
> https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

すみません。デプロイしました

**Comment by yasunamiura** [comment]
再度提出ありがとうございます！
挙動確認させて頂いたところ、前回同様の不備が見受けられましたので修正をお願いします！

[![Image from Gyazo](https://i.gyazo.com/f83d4f1cdc38814b9e7a1559262ca861.png)](https://gyazo.com/f83d4f1cdc38814b9e7a1559262ca861)

修正し次第、以下のChatSpace完了報告フォームを再度提出お願いします！
https://docs.google.com/forms/d/e/1FAIpQLSfNKbknajjCthhkGSyIkhspu2hOAxnESHweNLX2LQJdlO5vGw/viewform

**Comment by yasunamiura** [comment]
再度デプロイお願いしいます！

**Comment by fukuda-taichi** [comment]
> 再度デプロイお願いしいます！

何度もすみません。挙動確認できました

**Comment by yasunamiura** [comment]
ご提出ありがとうございます！
確認させて頂きましたが、修正箇所ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます！

**Comment by fukuda-taichi** [comment]
> ご提出ありがとうございます！
> 確認させて頂きましたが、修正箇所ございませんでしたのでLGTMとさせて頂きます🎉
> おめでとうございます！

ありがとうございます！
